name: Update Progress Bar

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows manual run

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Progress Bar
        run: |
          # Extract current day number from README
          DAY=$(grep -oP '(?<=Progress: )\d+(?=/100)' README.md)
          TOTAL=100
          BLOCKS=25
          GREEN=$((DAY * BLOCKS / TOTAL))
          EMPTY=$((BLOCKS - GREEN))
          PERCENT=$((DAY * 100 / TOTAL))

          BAR=$(printf '🟩%.0s' $(seq 1 $GREEN); printf '⬜%.0s' $(seq 1 $EMPTY))

          sed -i "/<!--START_PROGRESS_BAR-->/,/<!--END_PROGRESS_BAR-->/c\<!--START_PROGRESS_BAR-->\n$BAR  \n$GREEN / $BLOCKS Blocks — $PERCENT%\n<!--END_PROGRESS_BAR-->" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update progress bar for Day $DAY"
          git push
